=== Karakean/XML-Based/dtd.dtd
<!ELEMENT grzyby (podstawczaki,workowce,jadlospis,grzybobranie)>
        <!ELEMENT podstawczaki (grzyby_jadalne|grzyby_niejadalne|grzyby_trujace)*>
        <!ELEMENT grzyby_jadalne (gatunek)*>
        <!ELEMENT gatunek ((nazwa_polska|nazwa_lacinska),rodzina,rzad,klasa,opis,media)>
        <!ELEMENT nazwa_polska (#PCDATA)>
        <!ELEMENT nazwa_lacinska (#PCDATA)>
        <!ATTLIST gatunek
                chroniony (tak|nie) #IMPLIED
                rodzaj CDATA #REQUIRED
                zastosowanie CDATA "brak">
        <!ELEMENT rodzina (#PCDATA)>
        <!ELEMENT rzad (#PCDATA)>
        <!ELEMENT klasa (#PCDATA)>
        <!ELEMENT opis (#PCDATA)>
        <!ATTLIST opis
                zrodlo CDATA #REQUIRED>
        <!ELEMENT media (zdjecie)*>
        <!ELEMENT zdjecie (#PCDATA)>
        <!ATTLIST zdjecie
                zrodlo CDATA #REQUIRED>
        <!ELEMENT grzyby_niejadalne (gatunek)*>
        <!ELEMENT grzyby_trujace (gatunek)*>
        <!ELEMENT workowce (grzyby_jadalne)*>
        <!ELEMENT jadlospis (sniadanie,drugie_sniadanie,lunch,obiad,deser,podwieczorek,kolacja,podkurek,cena)*>
        <!ELEMENT sniadanie (#PCDATA)>
        <!ELEMENT drugie_sniadanie (#PCDATA)>
        <!ELEMENT lunch (#PCDATA)>
        <!ELEMENT obiad (pierwsze_danie,drugie_danie)*>
        <!ELEMENT pierwsze_danie (#PCDATA)>
        <!ELEMENT drugie_danie (#PCDATA)>
        <!ELEMENT deser (#PCDATA)>
        <!ELEMENT podwieczorek (#PCDATA)>
        <!ELEMENT kolacja (#PCDATA)>
        <!ELEMENT podkurek (#PCDATA)>
        <!ELEMENT cena (#PCDATA)>
        <!ELEMENT grzybobranie (#PCDATA|komentarz|ocena|pogoda|temperaturaK)*>
        <!ATTLIST grzybobranie
                %day;
                %month;
                rok CDATA #REQUIRED>
        <!ELEMENT komentarz (#PCDATA)>
        <!ELEMENT ocena (#PCDATA)>
        <!ELEMENT pogoda (#PCDATA)>
        <!ELEMENT temperaturaK (#PCDATA)>
        <!ENTITY opis_bs "Jest to gatunek często spotykany w Polsce, zwłaszcza w górach, rzadziej na niżu, zwykle rzadki w okolicach wielkich miast. Aromatyczny grzyb jadalny o szerokich zastosowaniach w kuchniach europejskich. Nadaje się do bezpośredniego spożycia, marynowania, suszenia i do wszelkich innych rodzajów przerobu.">
        <!ENTITY opis_d SYSTEM "drozdze.xml">
        <!ENTITY % day "dzien (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31) #REQUIRED">
        <!ENTITY % month "miesiac (1|2|3|4|5|6|7|8|9|10|11|12) #REQUIRED">

=== Karakean/XML-Based/xmldtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grzyby SYSTEM "dtd.dtd">
<grzyby>
	<podstawczaki>
		<grzyby_jadalne>
			<gatunek rodzaj="borowik" chroniony="nie" zastosowanie="przemysl_spozywczy">
				<nazwa_polska>Borowik szlachetny</nazwa_polska>
				<rodzina>borowikowate</rodzina>
				<rzad>borowikowce</rzad>
				<klasa>pieczarniaki</klasa>
				<opis zrodlo="https://pl.wikipedia.org/wiki/Borowik_szlachetny">&opis_bs;</opis>
				<media><zdjecie zrodlo="images/bs.jpg">borowik szlachetny</zdjecie></media>
			</gatunek>
		</grzyby_jadalne>
		<grzyby_niejadalne>
			<gatunek rodzaj="goryczak" chroniony="nie">
				<nazwa_polska>Goryczak żółciowy</nazwa_polska>
				<rodzina>borowikowate</rodzina>
				<rzad>borowikowce</rzad>
				<klasa>pieczarniaki</klasa>
				<opis zrodlo="https://www.ekologia.pl/srodowisko/przyroda/goryczak-zolciowy-opis-wystepowanie-i-zdjecia-grzyb-goryczak-zolciowy-ciekawostki,25878.html">Goryczak żółciowy (Tylopilus felleus) znany jest pod wieloma różnymi nazwami, z których znaczna część odwołuje się do charakterystycznego, intensywnego smaku miąższu: grzybek gorzki, zajączek gorzki, grzyb cierpki – to tylko niektóre przykłady. Popularna nazwa „szatan” odnosi się jednak wyłącznie do borowika szatańskiego, wcale niepodobnego wizualnie, który na dodatek w Polsce stanowi rzadkość, bowiem preferuje klimat ciepły i gleby bogate w wapń. Goryczaki żółciowe są natomiast w naszym kraju bardzo powszechne.</opis>
				<media><zdjecie zrodlo="images/gz.jpg">goryczak żółciowy</zdjecie></media>
			</gatunek>
		</grzyby_niejadalne>
		<grzyby_trujace>
			<gatunek rodzaj="muchomor" chroniony="nie">
				<nazwa_polska>Muchomor zielonawy</nazwa_polska>
				<rodzina>muchomorowate</rodzina>
				<rzad>pieczarkowce</rzad>
				<klasa>pieczarniaki</klasa>
				<opis zrodlo="https://pl.wikipedia.org/wiki/Muchomor_zielonawy">Gatunek grzybów pospolity w Polsce, jest dla ludzi silnie trujący, nawet przy zaawansowanym leczeniu spożycie bardzo często kończy się śmiercią. Dla wielu drobnych zwierząt, np. ślimaków i owadów jest nieszkodliwy</opis>
				<media><zdjecie zrodlo="images/ms.jpg">muchomor zielonawy</zdjecie></media>
			</gatunek>
		</grzyby_trujace>
	</podstawczaki>
	<workowce>
		<grzyby_jadalne>
			<gatunek rodzaj="drozdze" chroniony="nie" zastosowanie="przemysl_spozywczy,badania">
				<nazwa_polska>"lacinska">Saccharomyces cerevisiae</nazwa_polska>
				<rodzina>drozdzakowate</rodzina>
				<rzad>drozdzakowce</rzad>
				<klasa>drozdzaki</klasa>
				&opis_d;
				<media><zdjecie zrodlo="images/d.jpg">drożdże</zdjecie></media>
			</gatunek>
		</grzyby_jadalne>
	</workowce>
	<jadlospis>
		<sniadanie>tofucznica z grzybami</sniadanie>
		<drugie_sniadanie>grzyby smażone</drugie_sniadanie>
		<lunch>zapiekanka z grzybami</lunch>
		<obiad>
			<pierwsze_danie>zupa grzybowa</pierwsze_danie>
			<drugie_danie>kotlety grzybowe</drugie_danie>
		</obiad>
		<deser>lody grzybowe</deser>
		<podwieczorek>tarta grzybowa</podwieczorek>
		<kolacja>pierogi z grzybami</kolacja>
		<podkurek>grzyby w śmietanie</podkurek>
		<cena>4.20zł 0.50zł 3.14zł 5zł 6.66zł 6.90zł 22.72zł 10zł 15zł</cena>
	</jadlospis>
	<grzybobranie dzien="23" miesiac="10" rok="2020">
		<komentarz>raport z grzybobrania</komentarz>
		<ocena>udane</ocena>
		<ocena>10</ocena>
		<pogoda>słonecznie</pogoda>
		Temperatura w Kelwinach<temperaturaK>293</temperaturaK>
	</grzybobranie>
</grzyby>
